# -*- coding: utf-8 -*-
"""AMD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KcawAfxLRcemONOBHsTJ7mPokNWbQPYU
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

amd = yf.Ticker("AMD")

!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/data/amd.json

import json
with open('amd.json') as json_file:
    amd_info = json.load(json_file)
    # Print the type of data variable
    #print("Type:", type(apple_info))
amd_info

#Find the country
amd_info['country']

#Find the sector stock belongs to
amd_info['sector']

amd_stock_data = amd.history(period="max")

amd_stock_data.head()

first_day_volume = amd_stock_data.iloc[0]['Volume']

# Print the volume traded on the first day
print(f"Volume Traded on the First Day: {first_day_volume}")